# Generated by Django 2.1.7 on 2019-02-22 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190213_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productquestion',
            options={'verbose_name': 'Product Question', 'verbose_name_plural': 'Product Questions'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
